// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWHKdVhP-_lokOXf-_JgCWmrsH0_7H_Qs',
    appId: '1:548000609414:web:49b854fad9052b6adccd07',
    messagingSenderId: '548000609414',
    projectId: 'airbnbs-bba54',
    authDomain: 'airbnbs-bba54.firebaseapp.com',
    storageBucket: 'airbnbs-bba54.firebasestorage.app',
    measurementId: 'G-KWDKZ9EH8T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0lVuTfqCczspUN5rB4UKWLN61cWFFpuY',
    appId: '1:548000609414:android:9fc3c12e2f02cb29dccd07',
    messagingSenderId: '548000609414',
    projectId: 'airbnbs-bba54',
    storageBucket: 'airbnbs-bba54.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvrjukKYJYnqKnmhJMK9LPuL67T8s1TDk',
    appId: '1:548000609414:ios:93968ad22a611d43dccd07',
    messagingSenderId: '548000609414',
    projectId: 'airbnbs-bba54',
    storageBucket: 'airbnbs-bba54.firebasestorage.app',
    androidClientId: '548000609414-ur9lp8aksdvi77mao8926pmclep2rn60.apps.googleusercontent.com',
    iosClientId: '548000609414-d5n09cndkf2nmm28v4ns98age0hb46a8.apps.googleusercontent.com',
    iosBundleId: 'com.example.airbnbApp',
  );

}